[project]
name = "1-types"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.composites]
path = "contracts/composites.clar"
depends_on = []

[contracts.primitives]
path = "contracts/primitives.clar"
depends_on = []

[contracts.sequences]
path = "contracts/sequences.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
