[project]
name = "timelocked-wallet"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.timelocked-wallet]
path = "contracts/timelocked-wallet.clar"
depends_on = []
